[tool.poetry]
name = "temperature-api"
version = "0.1.0"
description = ""
authors = ["Andrew Romm <andrew.romm@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
flask = "^3.1.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
