apiVersion: v1
data:
  mongo-init.js: |
    db = db.getSiblingDB('telemetry_database');

    db.createUser({
        user: "root",
        pwd: "mongodb",
        roles: [{ role: "readWrite", db: "telemetry_database" }]
    });
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: mongo
  name: mongo-cm1
