apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: kafka1
  name: kafka1
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kafka1
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.35.0 (HEAD)
      labels:
        io.kompose.service: kafka1
    spec:
      containers:
        - env:
            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://kafka1:9092
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_CREATE_TOPICS
              value: forced.module.shutdown:3:2,telemetry.data:3:2,module.addition.topic:3:2,module.verification.topic:3:2,equipment.change.state.topic:3:2
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: PLAINTEXT
            - name: KAFKA_LISTENERS
              value: PLAINTEXT://0.0.0.0:9092
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper:2181
          image: wurstmeister/kafka
          name: kafka1
          ports:
            - containerPort: 9092
              protocol: TCP
          volumeMounts:
            - mountPath: /kafka/logs
              name: kafka1-data
      restartPolicy: Always
      volumes:
        - name: kafka1-data
          persistentVolumeClaim:
            claimName: kafka1-data
