apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: mongo
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mongo
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.35.0 (HEAD)
      labels:
        io.kompose.service: mongo
    spec:
      containers:
        - env:
            - name: MONGO_INITDB_DATABASE
              value: telemetry_database
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: mongodb
            - name: MONGO_INITDB_ROOT_USERNAME
              value: root
            - name: MONGO_URI
              value: mongodb://root:mongodb@mongo:27017/telemetry_database?authSource=admin
          image: mongo:latest
          name: mongo
          ports:
            - containerPort: 27017
              protocol: TCP
          volumeMounts:
            - mountPath: /data/db
              name: mongo-data
            - mountPath: /docker-entrypoint-initdb.d/mongo-init.js
              name: mongo-cm1
              subPath: mongo-init.js
      restartPolicy: Always
      volumes:
        - name: mongo-data
          persistentVolumeClaim:
            claimName: mongo-data
        - configMap:
            items:
              - key: mongo-init.js
                path: mongo-init.js
            name: mongo-cm1
          name: mongo-cm1
