apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: telemetry-service
  name: telemetry-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: telemetry-service
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.35.0 (HEAD)
      labels:
        io.kompose.service: telemetry-service
    spec:
      containers:
        - env:
            - name: KAFKA_BROKERS
              value: kafka1:9092,kafka2:9093,kafka3:9094
            - name: MONGO_URI
              value: mongodb://root:mongodb@mongo:27017/telemetry_database
          image: baydinvladislav/telemetry-service:latest
          name: telemetry-service
          ports:
            - containerPort: 8082
              protocol: TCP
      restartPolicy: Always
