services:
  postgres:
    image: postgres:15
    container_name: apps-postgres-1
    environment:
      POSTGRES_DB: smarthome
      POSTGRES_USER: smarthome
      POSTGRES_PASSWORD: smarthome
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  temperature-api:
    build: .
    container_name: apps-temperature-api-1
    ports:
      - "8081:8081"
    depends_on:
      - postgres

volumes:
  pgdata:
