version: "3.9"
services:
  temperature-api:
    build: .
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: smarthome
      POSTGRES_USER: smarthome
      POSTGRES_PASSWORD: smarthome

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: smarthome
      POSTGRES_PASSWORD: smarthome
      POSTGRES_DB: smarthome
    volumes:
      - ./smart_home/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
